### ISSUE TITLE
file browse modal is blank when team game fields are filled, but game hasn't been saved yet

### ISSUE THREAD

**Issue by hitjim** [devict/ictgj-voting#3]
Go to admin/teams/<id>/edit when no teams have been created yet (creating first team)
* enter team name - don't update team yet
* enter team game name - don't update yet
* enter description - don't update yet
* click "upload screenshot" button, file browse modal should come up without browse button, can only exit modal by refreshing... so it seems.

I guess to get here, I had to have created the team already, and opted to edit it from /admin/teams

**Comment by br0xen** [comment]
I accidentally referenced this issue in the pull request 14.
